# Production Docker Compose Configuration
# Loads environment variables from .env.production automatically
# Run with: docker compose -f docker-compose-im.yml up -d

services:
  db:
    image: mysql:8.0
    container_name: bsu_db_1
    restart: always
    env_file:
      - .env.production
    volumes:
      - db_data_1:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bsu_network

  backend:
    image: mohamedessam14/bsu_backend:v2.6
    container_name: bsu_backend_1
    volumes:
      - media_data:/app/media
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - .env.production
    networks:
      - bsu_network

  frontend:
    image: mohamedessam14/bsu_frontend:v2.6
    container_name: bsu_frontend_1
    volumes:
      - media_data:/usr/share/nginx/html/media
    ports:
      - "8081:80"
    depends_on:
      - backend
    restart: always
    networks:
      - bsu_network

volumes:
  db_data_1:
  media_data:


networks:
  bsu_network:
    driver: bridge
