services:
  db:
    image: mysql:8.0
    container_name: bsu_db_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bsu_db
      MYSQL_USER: bsu_user
      MYSQL_PASSWORD: bsu_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bsu_network

  backend:
    image: mohamedessam14/bsu_backend:v2.5
    container_name: bsu_backend_1
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - DATABASE_URL=mysql://bsu_user:bsu_password@db:3306/bsu_db
    networks:
      - bsu_network

  frontend:
    image: mohamedessam14/bsu_frontend:v2.4
    container_name: bsu_frontend_1
    ports:
      - "8081:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - bsu_network

volumes:
  db_data:


networks:
  bsu_network:
    driver: bridge
