services:
  db:
    image: mysql:8.0
    container_name: bsu_db_1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bsu_db
      MYSQL_USER: bsu_user
      MYSQL_PASSWORD: bsu_password
    volumes:
      - db_data_1:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bsu_backend_1
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      - DATABASE_URL=mysql://bsu_user:bsu_password@db:3306/bsu_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bsu_frontend_1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8081:5173"
    depends_on:
      - backend
    restart: always
    # phpmyadmin:
    #    image: phpmyadmin:latest
    #    container_name: bsu_phpmyadmin_1
    #    restart: always
    #    ports:
    #      - "8082:80"
    #    environment:
    #      PMA_HOST: db
    #      PMA_PORT: 3306
    #      MYSQL_ROOT_PASSWORD: root
    #    depends_on:
    #      db:
    #        condition: service_healthy

volumes:
  db_data_1:
